[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ikslavok/obsidian-zola __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Idi na početnu👆"
LANDING_DESCRIPTION = "Pretraži, otvori belešku iz mreže koja je prikazana u pozadini ili idi na sadržaj."
LANDING_PAGE = "pocetna"
LANDING_TITLE = "Dobrodošao u HIS bazu znanja 👋"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ikslavok/HISmaterijali"
SITE_TITLE = "HIS materijali 📕"
SITE_TITLE_TAB = ""
SITE_URL = "https://stunning-crostata-9734b6.netlify.app"
TIMEZONE = "Europe/Belgrade"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
SLUGIFY = "n"
HOME_GRAPH = "y"
PAGE_GRAPH = "y"
SIDEBAR_COLLAPSED = "true"
ROOT_SECTION_NAME = "M"