[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Click to steal some👆"
LANDING_DESCRIPTION = "I have nothing but intelligence."
LANDING_PAGE = "pocetna"
LANDING_TITLE = "I love obsidian-zola! 💖"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ikslavok/HISmaterijali"
SITE_TITLE = "Someone's Second 🧠"
SITE_TITLE_TAB = ""
SITE_URL = "https://stunning-crostata-9734b6.netlify.app"
TIMEZONE = "Europe/Belgrade"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
SLUGIFY = "y"
HOME_GRAPH = "y"
PAGE_GRAPH = "y"
SIDEBAR_COLLAPSED = "true"
ROOT_SECTION_NAME = "materijali"